### ISSUE TITLE
能否有计划考虑丰富功能

### ISSUE THREAD

**Issue by og-118-ao** [jqhph/easy-excel#2]
可以计划加入常用的合并单元格、设置单元格格式、固定表头一些基础功能呢？

**Comment by jqhph** [comment]
合并单元格这个目前还没考虑过要怎么做，大家有需求的话可以加入，如果有想法欢迎讨论；
设置单元格格式的功能已经有了，使用方法请参考文档；
固定表头这个功能目前实现不了。
