### ISSUE TITLE
请问导出功能中 是否可以图片功能

### ISSUE THREAD

**Issue by icehan2016** [jqhph/easy-excel#3]
请问导出功能中 是否可以图片功能

感谢

**Comment by jqhph** [comment]
https://github.com/box/spout/issues/137

**Comment by jqhph** [comment]
https://github.com/box/spout/issues/137

**Comment by jqhph** [comment]
这个功能暂不支持（后面可能会增加）。本项目目前是基于box/spout实现的，很遗憾box/spout不支持图片相关操作 https://github.com/box/spout/issues/137。
